# Generated by Django 3.1.7 on 2021-08-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'DS Người dùng'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_realtor',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/logo tgnp brown.jpg', upload_to='photos/%Y/%m/%d/', verbose_name='Ảnh đại diện'),
        ),
    ]
