# Generated by Django 3.1.7 on 2021-11-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210815_2058'),
        ('accounts', '0002_auto_20210622_2210'),
    ]

    operations = [
    ]
