# Generated by Django 3.1.7 on 2022-04-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210815_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/logo tgnp brown.jpg', upload_to='photos/%Y%m%d/', verbose_name='Ảnh đại diện'),
        ),
    ]
