# Generated by Django 3.1.7 on 2022-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20211109_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/logo tgnp brown.jpg', upload_to='photos/%Y%m%d/', verbose_name='Ảnh đại diện'),
        ),
    ]
