# Generated by Django 3.1.7 on 2021-08-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Nhóm người dùng',
                'verbose_name_plural': 'DS Nhóm người dùng',
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
