# Generated by Django 3.1.7 on 2022-04-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220419_0948'),
        ('accounts', '0006_auto_20220427_1519'),
    ]

    operations = [
    ]
