# Generated by Django 3.1.7 on 2022-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20220429_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/%Y%m%d/', verbose_name='Ảnh đại diện'),
        ),
    ]
