# Generated by Django 3.1.7 on 2022-05-27 10:40

import FunctionModule.accounts.models
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0009_auto_20220527_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tên nhóm')),
                ('permissions', models.ManyToManyField(blank=True, related_name='permissions2permissions', to='auth.Permission', verbose_name='Quyền sử dụng')),
            ],
            options={
                'verbose_name': 'Nhóm người dùng',
                'verbose_name_plural': 'DS Nhóm người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_point', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Điểm đầu tư')),
                ('investment_account', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Tài khoản có đầu tư (Triệu đồng)')),
                ('prestige_points', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Điểm uy tín')),
                ('potential_points', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Điểm tiềm năng')),
                ('bds_referral_point', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Điểm giới thiệu BĐS')),
                ('customer_referral_point', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Điểm giới thiệu khách')),
            ],
            options={
                'verbose_name': 'Điểm số',
                'verbose_name_plural': 'Điểm đạt được',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube',
        ),
        migrations.AddField(
            model_name='user',
            name='is_broker',
            field=models.BooleanField(default=False, verbose_name='MUỐN LÀM MÔI GIỚI'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_investor',
            field=models.BooleanField(default=False, verbose_name='MUỐN LÀM ĐẦU TƯ'),
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.AddField(
            model_name='point',
            name='user',
            field=models.OneToOneField(blank=True, db_constraint=FunctionModule.accounts.models.User, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
