# Generated by Django 3.1.7 on 2022-06-28 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0010_auto_20220527_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CustomGroup',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Đăng nhập lần cuối'),
        ),
    ]
