# Generated by Django 3.1.7 on 2022-06-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220629_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cus_user_permissions',
        ),
    ]
