# Generated by Django 3.1.7 on 2022-06-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0014_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['content_type__app_label', 'content_type__model', 'codename'], 'verbose_name': 'Quyền sử dụng', 'verbose_name_plural': 'DS Quyền sử dụng'},
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='customgroup', to='auth.Permission', verbose_name='Quyền sử dụng'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100, verbose_name='Mã chức năng'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django', to='contenttypes.contenttype', verbose_name='Chức năng'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên quyền'),
        ),
        migrations.AlterField(
            model_name='user',
            name='customgroup',
            field=models.ManyToManyField(blank=True, help_text='Nhóm quyền mà người dùng này được phân quyền', related_name='user_set', related_query_name='user', to='accounts.CustomGroup', verbose_name='Nhóm người dùng'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Xác định quyền cho người dùng này.', related_name='user_set', related_query_name='user', to='accounts.Permission', verbose_name='Quyền người dùng'),
        ),
    ]
