# Generated by Django 3.1.7 on 2022-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220629_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customgroup',
            field=models.ManyToManyField(blank=True, help_text='Nhóm quyền mà người dùng này được phân quyền.', related_name='user_set', related_query_name='user', to='accounts.CustomGroup', verbose_name='Nhóm người dùng'),
        ),
    ]
