# Generated by Django 3.1.14 on 2022-06-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220629_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='customgroup', to='accounts.Permission', verbose_name='Quyền sử dụng'),
        ),
    ]
