# Generated by Django 3.1.14 on 2022-08-04 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220630_0150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customgroup',
            managers=[
            ],
        ),
    ]
