# Generated by Django 3.1.14 on 2022-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220804_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tên nhóm')),
                ('permissions', models.ManyToManyField(blank=True, related_name='Group', to='accounts.Permission', verbose_name='Quyền sử dụng')),
            ],
            options={
                'verbose_name': 'Nhóm người dùng',
                'verbose_name_plural': 'DS Nhóm người dùng',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='customgroup',
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
