# Generated by Django 3.1.14 on 2022-09-01 08:00

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0021_auto_20220901_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Quyền sử dụng',
                'verbose_name_plural': 'DS Quyền sử dụng',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
