# Generated by Django 3.1.14 on 2022-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20220901_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Xác định quyền cho người dùng này.', related_name='user_permissions', related_query_name='user', to='accounts.Permissions', verbose_name='Quyền người dùng'),
        ),
    ]
