# Generated by Django 3.1.14 on 2022-09-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20220902_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Người dùng--Nhóm', 'verbose_name_plural': 'Người dùng--Nhóm'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'Người dùng--Quyền sử dụng', 'verbose_name_plural': 'Người dùng--Quyền sử dụng'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
    ]
