# Generated by Django 3.1.14 on 2022-11-08 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220904_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'địa chỉ email', 'verbose_name_plural': 'địa chỉ email'},
        ),
        migrations.AlterModelOptions(
            name='emailconfirmation',
            options={'verbose_name': 'Xác nhận email', 'verbose_name_plural': 'Xác nhận email'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Phân Nhóm Người dùng', 'verbose_name_plural': 'Phân Nhóm Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'Phân Quyền Người dùng', 'verbose_name_plural': 'Phân Quyền Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='socialapp',
            options={'verbose_name': 'ứng dụng xã hội', 'verbose_name_plural': 'ứng dụng xã hội'},
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='địa chỉ e-mail'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='chính'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='người sử dụng'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='đã xác minh'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.emailaddress', verbose_name='địa chỉ e-mail'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='sent',
            field=models.DateTimeField(null=True, verbose_name='Gửi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/avatar/', verbose_name='Ảnh đại diện'),
        ),
    ]
