version: "3.9"

services:
  redis:
     image: 'redis:latest'
     restart: on-failure
  db:
    image: 'kartoza/postgis:13-3.1'
    environment:
      - POSTGRES_DBNAME=real_estate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
  web:
    build: .
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    command:  bash -c "service ssh restart;python manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "8889:8889"
      - "2222:22"
    depends_on:
      - db
