version: '3.9'

services:
  db:
    image: 'kartoza/postgis:13-3.1'
    environment:
      - POSTGRES_DBNAME=tgnp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bBtv7V96uSV590
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data:/var/lib/postgresql
      - ./data/db:/home/db
    ports:
      - "5432:5432"
    #expose:
    #  - "5432"
    restart: on-failure
  redis:
    image: 'redis:7.0'
    restart: on-failure
    expose:
      - "6379"
  nginx:
    restart: always
    image: nginx:1.22
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './deploy/nginx/conf.d.production:/etc/nginx/conf.d'
      - './deploy/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './compiled_staticfiles:/staticfiles'
      - './media:/media'
      - '/data/certbot/conf:/etc/letsencrypt'
      - '/data/certbot/www:/var/www/certbot'
    depends_on:
      - web
    #command: "nginx -s reload"
    tty: true
  certbot:
    image: certbot/certbot
    volumes:
      - '/data/certbot/conf:/etc/letsencrypt'
      - '/data/certbot/www:/var/www/certbot'
      - './deploy/renew.sh:/renew.sh'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    #network_mode: "host"
    #tty: true
  search_engine:
    image: 'getmeili/meilisearch:v0.21.0rc3'
    ports:
      - '7700:7700'
    volumes:
      - ./data/search/ms:/data.ms
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
      - MEILI_NO_ANALYTICS=true
      - MEILI_NO_SENTRY=true
    restart: on-failure
  web:
    restart: always
    build:
      context: .
      dockerfile: deploy/dockerfile.production
    command: bash -c "gunicorn --bind 0.0.0.0:8888 TownhouseWorldRealestate.wsgi:application -k gevent"
    env_file:
      - .env
    volumes:
      - ./:/app
    #ports:
    #  - "8888:8888"
    expose:
      - "8888"
    depends_on:
      - db
      - redis
      - search_engine
    tty: true

volumes:
  db-data:
    driver: local
