# Generated by Django 3.1.7 on 2021-05-09 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0006_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã giao dịch', max_length=13)),
                ('comment', models.TextField(help_text='Chú thích')),
                ('price', models.FloatField(help_text='Giá')),
                ('quantity', models.FloatField(help_text='Số lượng')),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, choices=[('find', 'Tìm kiếm'), ('oder', 'Đặt hàng'), ('saw', 'Đã xem'), ('negotiate', "'Đàm phán"), ('deposit', 'Đặt cọc'), ('transfer', 'Sang nhượng'), ('cancelDeposit', 'Bỏ cọc'), ('cancelTransaction', 'Huỷ giao dịch')], default='find', help_text='Lý do giao dịch', max_length=25)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.listing', verbose_name='Bất động sản')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
        ),
    ]
