# Generated by Django 3.1.7 on 2022-04-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210815_1839'),
        ('customers', '0002_auto_20220429_2209'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='location',
            new_name='caring_area',
        ),
        # migrations.RemoveField(
        #     model_name='transaction',
        #     name='user',
        # ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Đang giao dịch'), ('pause', 'Tạm dừng'), ('cancelTransaction', 'Huỷ'), ('completed', 'Hoàn thành')], default='active', max_length=25, verbose_name='Trạng thái giao dịch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='house_type',
            field=models.CharField(blank=True, choices=[('street_house', 'Nhà mặt phố'), ('town_house', 'Nhà phố'), ('loft_house', 'Nhà 1 tầng/Cấp 4'), ('shop_house', 'Cửa hàng/ShopHouse'), ('apartment', 'Căn hộ/Nhà tập thể/CCMN'), ('villa', 'Biệt thự'), ('plot', 'Liền kề/Phân lô/Dịch vụ'), ('land', 'Đất nền'), ('building', 'Toà nhà'), ('building_business', 'Toà nhà kinh doanh'), ('office', 'Văn phòng'), ('office_tel', 'Văn phòng khách sạn'), ('condo_tel', 'Căn hộ khách sạn'), ('service_apartment', 'Căn hộ dịch vụ'), ('pent_house', 'Căn hộ áp mái'), ('villa_rest', 'Biệt thự nghỉ dưỡng'), ('land_business', 'Mặt bằng kinh doanh'), ('industrial_land', 'Đất công nghiệp'), ('warehouse_workshop', 'Kho xưởng'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Loại BĐS'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor', verbose_name='Chuyên viên quản lý'),
        ),
    ]
