# Generated by Django 3.1.7 on 2021-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('find', 'Tìm kiếm'), ('oder', 'Đặt hàng'), ('saw', 'Đã xem'), ('negotiate', 'Đàm phán'), ('deposit', 'Đặt cọc'), ('transfer', 'Sang nhượng'), ('cancelDeposit', 'Bỏ cọc'), ('cancelTransaction', 'Huỷ giao dịch')], default='find', help_text='Lý do giao dịch', max_length=25),
        ),
    ]
