# Generated by Django 3.1.7 on 2021-08-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210803_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Giao dịch BĐS', 'verbose_name_plural': 'DS Giao dịch'},
        ),
    ]
