# Generated by Django 3.1.7 on 2021-09-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210815_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date'], 'verbose_name': 'Giao dịch BĐS', 'verbose_name_plural': 'DS Giao dịch'},
        ),
    ]
