# Generated by Django 3.1.7 on 2021-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210903_2348'),
    ]

    operations = [

    ]
