# Generated by Django 3.1.7 on 2021-08-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210816_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='district',
            new_name='location',
        ),
    ]
