# Generated by Django 3.1.7 on 2021-09-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210904_1714'),
        ('transactions', '0005_transactionhistory_status'),
    ]

    operations = [
    ]
