# Generated by Django 3.1.7 on 2021-08-24 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210815_1839'),
        ('transactions', '0006_auto_20210820_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='house_type',
            field=models.CharField(blank=True, choices=[('street_house', 'Nhà mặt phố'), ('town_house', 'Nhà trong ngõ'), ('loft_house', 'Nhà gác xép/Cấp 4'), ('shop_house', 'Cửa hàng'), ('building', 'Toà nhà'), ('building_business', 'Toà nhà kinh doanh'), ('office', 'Văn phòng'), ('office_tel', 'Văn phòng khách sạn'), ('condo_tel', 'Căn hộ khách sạn'), ('apartment', 'Căn hộ'), ('service_apartment', 'Căn hộ dịch vụ'), ('pent_house', 'Căn hộ áp mái'), ('villa', 'Biệt thự'), ('villa_rest', 'Biệt thự nghỉ dưỡng'), ('land', 'Đất nền'), ('land_business', 'Mặt bằng kinh doanh'), ('plot', 'Đất phân lô'), ('industrial_land', 'Đất công nghiệp'), ('warehouse_workshop', 'Kho xưởng'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Loại BĐS quan tâm'),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('feedback', 'Trả lời khách'), ('meet', 'Dẫn khách'), ('negotiate', 'Đàm phán'), ('deposit', 'Đặt cọc'), ('cancelDeposit', 'Bỏ cọc'), ('contract', 'Ký hợp đồng'), ('cancelTransaction', 'Huỷ hợp đồng'), ('completed', 'Hoàn tất giao dịch')], default='feedback', max_length=25, verbose_name='Lý do giao dịch')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Diễn giải thêm')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Thời gian phát sinh giao dịch')),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor', verbose_name='Chuyên viên thực hiện')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transaction', verbose_name='Giao dịch')),
            ],
            options={
                'verbose_name': 'Lịch sử Giao dịch',
                'verbose_name_plural': 'DS Lịch sử Giao dịch',
                'ordering': ['date'],
            },
        ),
    ]
