# Generated by Django 3.1.7 on 2022-04-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20220430_1441'),
    ]

