# Generated by Django 3.1.7 on 2022-05-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20220430_1444'),
        ('transactions', '0002_auto_20220429_2209'),
    ]

    operations = [
    ]
