# Generated by Django 3.1.7 on 2022-05-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_merge_20220501_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='house_type',
            field=models.CharField(blank=True, choices=[('street_house', 'Nhà mặt phố'), ('town_house', 'Nhà phố'), ('loft_house', 'Nhà 1 tầng/Cấp 4'), ('shop_house', 'Cửa hàng/ShopHouse'), ('apartment', 'Căn hộ/Nhà tập thể/CCMN'), ('villa', 'Biệt thự'), ('plot', 'Liền kề/Phân lô/Dịch vụ'), ('land', 'Đất nền'), ('building', 'Toà nhà'), ('building_business', 'Toà nhà kinh doanh'), ('office', 'Văn phòng'), ('office_tel', 'Văn phòng khách sạn'), ('condo_tel', 'Căn hộ khách sạn'), ('service_apartment', 'Căn hộ dịch vụ'), ('pent_house', 'Căn hộ áp mái'), ('villa_rest', 'Biệt thự nghỉ dưỡng'), ('land_business', 'Mặt bằng kinh doanh'), ('industrial_land', 'Đất công nghiệp'), ('warehouse_workshop', 'Kho xưởng'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Loại BĐS quan tâm'),
        ),
    ]
