# Generated by Django 3.1.7 on 2022-05-13 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20220513_1023'),
        ('realtors', '0003_auto_20210815_1839'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0019_auto_20220513_1023'),
        ('transactions', '0013_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='customers.customer', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='listings.listing', verbose_name='Bất động sản'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='realtors.realtor', verbose_name='Chuyên viên quản lý'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='request_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Giá kỳ vọng/Giá chào'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trantype',
            field=models.CharField(choices=[('contact', 'Liên hệ'), ('view', 'Liên hệ xem BĐS'), ('oder', 'Đặt hàng'), ('buy', 'Mua'), ('sell', 'Bán'), ('rent', 'Thuê'), ('lease', 'Cho thuê'), ('intro_estate', 'Giới thiệu BĐS'), ('intro_custo', 'Giới thiệu Khách')], default='contact', max_length=25, verbose_name='Loại giao dịch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
