# Generated by Django 3.1.7 on 2022-05-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20220513_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ['date'], 'verbose_name': 'Lịch sử Giao dịch', 'verbose_name_plural': 'Lịch sử Giao dịch'},
        ),
    ]
