# Generated by Django 3.1.14 on 2022-09-03 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20220527_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date'], 'verbose_name': 'Giao dịch BĐS', 'verbose_name_plural': 'Giao dịch BĐS'},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ['date'], 'verbose_name': 'Giao dịch BĐS--Tương tác khách hàng', 'verbose_name_plural': 'Giao dịch BĐS--Tương tác khách hàng'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Ngày giao dịch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Thông điệp khách hàng'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Thời gian tương tác'),
        ),
    ]
