# Generated by Django 3.1.14 on 2022-11-08 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20220904_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ['date'], 'verbose_name': 'Xử lý Giao dịch', 'verbose_name_plural': 'Xử lý Giao dịch'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Diễn giải'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Thời gian phản hồi'),
        ),
    ]
