# Generated by Django 3.1.7 on 2021-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=0, default='100', max_digits=5, null=True, verbose_name='Số tiền trích thưởng (triệu)'),
        ),
    ]
