# Generated by Django 3.1.7 on 2021-08-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'DS Bất động sản'},
        ),
    ]
