# Generated by Django 3.1.7 on 2021-05-10 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.CharField(help_text='Được điền tự động và duy nhất', max_length=50, unique=True, verbose_name='Mã BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='direction',
            field=models.CharField(choices=[('east', 'Đông'), ('east-south', 'Đông - Nam'), ('south', 'Nam'), ('west-south', 'Tây - Nam'), ('west', 'Tây'), ('west-north', 'Tây - Bắc'), ('north', 'Bắc'), ('east-north', 'Đông - Bắc')], default='east', max_length=12, verbose_name='Hướng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lane_width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Rộng mặt đường/ngõ (m)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Giá chào (tỷ)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='registration_type',
            field=models.CharField(choices=[('red_book', 'Sổ Đỏ'), ('pink_book', 'Sổ Hồng'), ('dont_book', 'Chưa làm sổ')], default='red_book', max_length=20, verbose_name='Loại đăng ký'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Giá Hạ chào (tỷ)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.CharField(help_text='Tên đường, phố', max_length=125, null=True, verbose_name='Phố'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='[Tên phố - Quận/Huyện] [Diện tích - Tầng/Đất/CC - Mặt tiền] [Ngõ] [Giá]', max_length=200, verbose_name='Tên BĐS'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='Nhà Phố độc quyền'),
        ),
        migrations.AddField(
            model_name='listing',
            name='transaction_type',
            field=models.CharField(choices=[('sell', 'Bán'), ('for_rent', 'Cho thuê'), ('project', 'Dự án')], default='sell', max_length=20, verbose_name='Hình thức giao dịch'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_type',
            field=models.CharField(choices=[('street_house', 'Nhà mặt phố'), ('city_house', 'Nhà phố'), ('shop_house', 'Cửa hàng'), ('building', 'Toà nhà'), ('office', 'Văn phòng'), ('apartment', 'Căn hộ'), ('villa', 'Biệt thự'), ('land', 'Đất nền')], default='city_house', max_length=20, verbose_name='Loại nhà'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='registration_type',
            field=models.CharField(choices=[('red_book', 'Sổ Đỏ'), ('pink_book', 'Sổ Hồng'), ('dont_book', 'Chưa làm sổ')], default='red_book', max_length=20, verbose_name='Loại chứng nhận'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='direction',
            field=models.CharField(choices=[('east', 'Đông'), ('south-east', 'Đông - Nam'), ('south', 'Nam'), ('south-west', 'Tây - Nam'), ('west', 'Tây'), ('north-west', 'Tây - Bắc'), ('north', 'Bắc'), ('north-east', 'Đông - Bắc')], default='east', max_length=12, verbose_name='Hướng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Diện tích khuôn viên'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('red_book', 'Sổ Đỏ'), ('pink_book', 'Sổ Hồng'), ('dont_book', 'Chưa làm sổ')], default='red_book', max_length=20, null=True, verbose_name='Loại chứng nhận'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='road_type',
            field=models.CharField(choices=[('alley_car', 'Ngõ ô tô'), ('alley_bike', 'Ngõ xe máy'), ('alley_tribike', 'Ngõ Ba gác'), ('street_surface', 'Mặt tiền phố')], default='street_surface', max_length=20, verbose_name='Loại mặt tiền'),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('selling', 'Còn bán'), ('stop_selling', 'Dừng bán'), ('sold', 'Đã bán'), ('sale', 'Hạ chào')], default='selling', max_length=20, verbose_name='Tình trạng BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số phòng ngủ'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='Diện tích khuôn viên'),
        ),
        migrations.AddField(
            model_name='listing',
            name='urban_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khu đô thị/Khu dân cư'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phường/Xã'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Giá chào (tỷ)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Giá Hạ chào (tỷ)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.CharField(help_text='Được điền tự động và duy nhất', max_length=80, unique=True, verbose_name='Mã BĐS'),
        ),
    ]
