# Generated by Django 3.1.7 on 2021-08-07 04:43

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210803_1951'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['street', 'address'], name='listings_li_street_3c6499_gin'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['code'], name='listings_li_code_013a35_btree'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['bedrooms', 'bathrooms', 'direction'], name='listings_li_bedroom_14151d_btree'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['state', 'district', 'ward'], name='listings_li_state_6f187a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['house_type', 'transaction_type'], name='listings_li_house_t_a0d1ef_idx'),
        ),
    ]
