# Generated by Django 3.1.6 on 2021-03-20 15:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_20210317_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.AddField(
            model_name='listing',
            name='area_unit',
            field=models.CharField(default='m2', max_length=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Mã nhà'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='direction',
            field=models.CharField(choices=[('east', 'Đông'), ('west', 'Tây'), ('south', 'Nam'), ('north', 'Bắc')], default='east', max_length=12, verbose_name='Hướng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(default='', max_length=50, verbose_name='Quận/Huyện'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Thông tin khác'),
        ),
        migrations.AddField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số tầng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='house_type',
            field=models.CharField(choices=[('city_house', 'Nhà phố'), ('villa', 'Biệt thự'), ('land', 'Đất nền'), ('apartment', 'Chung cư'), ('project', 'Dự án')], default='city_house', max_length=20, verbose_name='Loại nhà'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác minh thông tin nhà'),
        ),
        migrations.AddField(
            model_name='listing',
            name='lane_width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Diện tích mặt đường/ngõ'),
        ),
        migrations.AddField(
            model_name='listing',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Chiều dài'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='registration_type',
            field=models.CharField(choices=[('red_book', 'Sổ Đỏ'), ('pink_book', 'Sổ Hồng')], default='red_book', max_length=20, verbose_name='Loại đăng ký'),
        ),
        migrations.AddField(
            model_name='listing',
            name='road_type',
            field=models.CharField(choices=[('alley_car', 'Ngõ ô tô'), ('alley_bike', 'Ngõ xe máy'), ('street_surface', 'Mặt tiền phố')], default='street_surface', max_length=20, verbose_name='Loại mặt tiền'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá Khuyến mãi'),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(default='', max_length=125, verbose_name='Địa chỉ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='ward',
            field=models.CharField(default='', max_length=50, verbose_name='Phường/Xã'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Chiều rộng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ đầy đủ'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Diện tích phòng tắm'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số phòng ngủ'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Diện tích vườn (m2)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Thành phố/Tỉnh'),
        ),
    ]
