# Generated by Django 3.1.6 on 2021-03-23 01:53

import datetime
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    replaces = [('listings', '0003_auto_20210320_1535'), ('listings', '0004_auto_20210321_0231'), ('listings', '0005_auto_20210322_1638')]

    dependencies = [
        ('listings', '0002_20210317_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.AddField(
            model_name='listing',
            name='direction',
            field=models.CharField(choices=[('east', 'Đông'), ('west', 'Tây'), ('south', 'Nam'), ('north', 'Bắc')], default='east', max_length=12, verbose_name='Hướng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(default='', max_length=50, verbose_name='Quận/Huyện'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số tầng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='house_type',
            field=models.CharField(choices=[('city_house', 'Nhà phố'), ('villa', 'Biệt thự'), ('land', 'Đất nền'), ('apartment', 'Chung cư'), ('project', 'Dự án')], default='city_house', max_length=20, verbose_name='Loại nhà'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác minh thông tin nhà'),
        ),
        migrations.AddField(
            model_name='listing',
            name='lane_width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Diện tích mặt đường/ngõ'),
        ),
        migrations.AddField(
            model_name='listing',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Chiều dài'),
        ),
        migrations.AddField(
            model_name='listing',
            name='registration_type',
            field=models.CharField(choices=[('red_book', 'Sổ Đỏ'), ('pink_book', 'Sổ Hồng')], default='red_book', max_length=20, verbose_name='Loại đăng ký'),
        ),
        migrations.AddField(
            model_name='listing',
            name='road_type',
            field=models.CharField(choices=[('alley_car', 'Ngõ ô tô'), ('alley_bike', 'Ngõ xe máy'), ('street_surface', 'Mặt tiền phố')], default='street_surface', max_length=20, verbose_name='Loại mặt tiền'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá Khuyến mãi'),
        ),
        migrations.AddField(
            model_name='listing',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Chiều rộng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ đầy đủ'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Diện tích phòng tắm'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số phòng ngủ'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Diện tích vườn (m2)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Thành phố/Tỉnh'),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.AddField(
            model_name='listing',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã nhà'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Diện tích'),
        ),
        migrations.AddField(
            model_name='listing',
            name='area_unit',
            field=models.CharField(choices=[('m2', 'm2')], default='m2', max_length=5, verbose_name='Đơn vị diện tích'),
        ),
        migrations.AddField(
            model_name='listing',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Thông tin khác'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(105.8401439, 21.0334474), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Diện tích vườn'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('01', 'Hà Nội'), ('02', 'Hà Giang'), ('04', 'Cao Bằng'), ('06', 'Bắc Kạn'), ('08', 'Tuyên Quang'), ('10', 'Lào Cai'), ('11', 'Điện Biên'), ('12', 'Lai Châu'), ('14', 'Sơn La'), ('15', 'Yên Bái'), ('17', 'Hoà Bình'), ('19', 'Thái Nguyên'), ('20', 'Lạng Sơn'), ('22', 'Quảng Ninh'), ('24', 'Bắc Giang'), ('25', 'Phú Thọ'), ('26', 'Vĩnh Phúc'), ('27', 'Bắc Ninh'), ('30', 'Hải Dương'), ('31', 'Hải Phòng'), ('33', 'Hưng Yên'), ('34', 'Thái Bình'), ('35', 'Hà Nam'), ('36', 'Nam Định'), ('37', 'Ninh Bình'), ('38', 'Thanh Hóa'), ('40', 'Nghệ An'), ('42', 'Hà Tĩnh'), ('44', 'Quảng Bình'), ('45', 'Quảng Trị'), ('46', 'Thừa Thiên Huế'), ('48', 'Đà Nẵng'), ('49', 'Quảng Nam'), ('51', 'Quảng Ngãi'), ('52', 'Bình Định'), ('54', 'Phú Yên'), ('56', 'Khánh Hòa'), ('58', 'Ninh Thuận'), ('60', 'Bình Thuận'), ('62', 'Kon Tum'), ('64', 'Gia Lai'), ('66', 'Đắk Lắk'), ('67', 'Đắk Nông'), ('68', 'Lâm Đồng'), ('70', 'Bình Phước'), ('72', 'Tây Ninh'), ('74', 'Bình Dương'), ('75', 'Đồng Nai'), ('77', 'Bà Rịa - Vũng Tàu'), ('79', 'Hồ Chí Minh'), ('80', 'Long An'), ('82', 'Tiền Giang'), ('83', 'Bến Tre'), ('84', 'Trà Vinh'), ('86', 'Vĩnh Long'), ('87', 'Đồng Tháp'), ('89', 'An Giang'), ('91', 'Kiên Giang'), ('92', 'Cần Thơ'), ('93', 'Hậu Giang'), ('94', 'Sóc Trăng'), ('95', 'Bạc Liêu'), ('96', 'Cà Mau')], default='01', max_length=50, verbose_name='Thành phố/Tỉnh'),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(help_text='Số nhà, ngõ, phố', max_length=125, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='listing',
            name='ward',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phường/Xã'),
        ),
    ]
