# Generated by Django 3.1.6 on 2021-03-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210320_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã nhà'),
        ),
    ]
