# Generated by Django 3.1.7 on 2021-08-15 11:39

import FunctionModule.listings.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210807_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractimage',
            options={'verbose_name': 'Ảnh chụp hợp đồng, sổ đỏ', 'verbose_name_plural': 'Ảnh hợp đồng, sổ đỏ'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Bất động sản', 'verbose_name_plural': 'DS Bất động sản'},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'verbose_name': 'Ảnh chụp BDS', 'verbose_name_plural': 'Ảnh Bất động sản'},
        ),
        migrations.AlterModelOptions(
            name='listingvideo',
            options={'verbose_name': 'Đường dẫn video Youtube', 'verbose_name_plural': 'Đường dẫn video Youtube'},
        ),
        migrations.AlterField(
            model_name='contractimage',
            name='photo',
            field=models.ImageField(upload_to=FunctionModule.listings.models.get_image_path, verbose_name='Link Ảnh'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='photo',
            field=models.ImageField(upload_to=FunctionModule.listings.models.get_image_path, verbose_name='Ảnh BĐS'),
        ),
        migrations.AlterField(
            model_name='listingvideo',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing', verbose_name='BĐS'),
        ),
        migrations.AlterField(
            model_name='listingvideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Link video'),
        ),
    ]
