# Generated by Django 3.1.7 on 2021-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210815_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='house_type',
            field=models.CharField(choices=[('street_house', 'Nhà mặt phố'), ('town_house', 'Nhà trong ngõ'), ('loft_house', 'Nhà gác xép/Cấp 4'), ('shop_house', 'Cửa hàng'), ('building', 'Toà nhà'), ('building_business', 'Toà nhà kinh doanh'), ('office', 'Văn phòng'), ('office_tel', 'Văn phòng khách sạn'), ('condo_tel', 'Căn hộ khách sạn'), ('apartment', 'Căn hộ'), ('service_apartment', 'Căn hộ dịch vụ'), ('pent_house', 'Căn hộ áp mái'), ('villa', 'Biệt thự'), ('villa_rest', 'Biệt thự nghỉ dưỡng'), ('land', 'Đất nền'), ('land_business', 'Mặt bằng kinh doanh'), ('plot', 'Đất phân lô'), ('industrial_land', 'Đất công nghiệp'), ('warehouse_workshop', 'Kho xưởng'), ('other', 'Khác')], default='town_house', max_length=20, verbose_name='Loại BĐS'),
        ),
    ]
