# Generated by Django 3.1.7 on 2021-09-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210824_1742'),
        ('listings', '0005_auto_20210824_2037'),
    ]

    operations = [
    ]
