# Generated by Django 3.1.7 on 2021-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_merge_20210903_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='furnish_type',
            field=models.CharField(blank=True, choices=[('furnished', 'Đủ đồ đạc'), ('semi-furnished', 'Một số đồ đạc'), ('unfurnished', 'Không có đồ đạc')], default='semi-furnished', max_length=20, null=True, verbose_name='Có đồ đạc?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('red_book', 'Sổ Đỏ'), ('pink_book', 'Sổ Hồng'), ('dont_book', 'Chưa làm sổ'), ('other', 'Khác')], default='red_book', max_length=20, null=True, verbose_name='Loại chứng nhận'),
        ),
    ]
