# Generated by Django 3.1.7 on 2021-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210903_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='construction',
            field=models.CharField(choices=[('release', 'Đã hoàn thiện'), ('under_construction', 'Đang thi công'), ('pre_release', 'Sắp thi công'), ('other', 'Khác')], default='release', max_length=20, null=True, verbose_name='Tình trạng xây dựng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('garage', 'Có gara ô tô'), ('off_street', 'Đỗ trước nhà'), ('street', 'Đỗ ngoài đường'), ('none', 'Không có chỗ đỗ'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Có chỗ đỗ ô tô không?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Xây mới'), ('old', 'Nhà cũ'), ('other', 'Khác')], default='old', max_length=20, null=True, verbose_name='Tình trạng BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furnish_type',
            field=models.CharField(blank=True, choices=[('furnished', 'Đủ đồ đạc'), ('semi_furnished', 'Một số đồ đạc'), ('unfurnished', 'Không có đồ đạc')], default='semi_furnished', max_length=20, null=True, verbose_name='Có kèm đồ đạc?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.CharField(blank=True, help_text='Điền năm hoàn thành xây dựng và Tỷ lệ % sử dụng còn lại', max_length=50, null=True, verbose_name='Năm xây dựng và tỉ lệ sử dụng còn lại'),
        ),
    ]
