# Generated by Django 3.1.7 on 2021-11-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20211025_0118'),
    ]

    operations = [
    ]
