# Generated by Django 3.1.7 on 2021-11-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20211109_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='direction',
            field=models.CharField(blank=True, choices=[('east', 'Đông'), ('south-east', 'Đông - Nam'), ('south', 'Nam'), ('south-west', 'Tây - Nam'), ('west', 'Tây'), ('north-west', 'Tây - Bắc'), ('north', 'Bắc'), ('north-east', 'Đông - Bắc')], max_length=20, null=True, verbose_name='Hướng'),
        ),
    ]
