# Generated by Django 3.1.7 on 2021-11-18 15:04

import datetime
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20211109_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Diện tích (m2)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area_real',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Diện tích thực tế(m2)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày đăng bán/cho thuê'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['street', 'code'], name='listings_li_street_8ec4e8_gin'),
        ),
    ]
