# Generated by Django 3.1.7 on 2022-04-29 15:14

from django.conf import settings
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0003_auto_20210815_1839'),
        ('listings', '0014_auto_20211118_2204'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='listing',
        #     name='average_price',
        #     field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Giá TB/m2 (triệu)'),
        # ),
        # migrations.AddField(
        #     model_name='listing',
        #     name='priority',
        #     field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Thứ tự ưu tiên đăng'),
        # ),
        # migrations.AddField(
        #     model_name='listing',
        #     name='user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Người thêm BĐS'),
        # ),
        migrations.AlterField(
            model_name='listing',
            name='bonus_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default='3', max_digits=2, null=True, verbose_name='Tỷ lệ trích thưởng (%)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.CharField(help_text='Chữ cái đầu Loại BĐS + 2 số cuối Năm Tháng + tên viết tắt Chuyên viên + Số BĐS của ĐC', max_length=80, unique=True, verbose_name='Mã BĐS (VIẾT HOA)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Xây mới'), ('old', 'Nhà cũ'), ('raw', 'Xây thô'), ('land', 'Đất nền'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Tình trạng BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='construction',
            field=models.CharField(blank=True, choices=[('release', 'Đã hoàn thiện'), ('under_construction', 'Đang thi công'), ('pre_release', 'Sắp thi công'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Tình trạng xây dựng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default=' Chú ý: Tất cả thông tin được đăng bởi TGNP đều là thông tin thật, xác thực chính xác.', help_text='Mô tả giới thiệu về BĐS ', verbose_name='Mô tả cho khách về bất động sản'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='extra_data',
            field=models.TextField(blank=True, help_text='Ghi các thông tin mô tả đầy đủ của đầu chủ về chủ nhà hoặc các yếu tố khác liên quan đến tương tác với Chuyên viên...', null=True, verbose_name='Mô tả bđs của chuyên viên'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49)], default='0', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Số tầng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_type',
            field=models.CharField(choices=[('street_house', 'Nhà mặt phố'), ('town_house', 'Nhà phố'), ('loft_house', 'Nhà 1 tầng/Cấp 4'), ('shop_house', 'Cửa hàng/ShopHouse'), ('apartment', 'Căn hộ/Nhà tập thể/CCMN'), ('villa', 'Biệt thự'), ('plot', 'Liền kề/Phân lô/Dịch vụ'), ('land', 'Đất nền'), ('building', 'Toà nhà'), ('building_business', 'Toà nhà kinh doanh'), ('office', 'Văn phòng'), ('office_tel', 'Văn phòng khách sạn'), ('condo_tel', 'Căn hộ khách sạn'), ('service_apartment', 'Căn hộ dịch vụ'), ('pent_house', 'Căn hộ áp mái'), ('villa_rest', 'Biệt thự nghỉ dưỡng'), ('land_business', 'Mặt bằng kinh doanh'), ('industrial_land', 'Đất công nghiệp'), ('warehouse_workshop', 'Kho xưởng'), ('other', 'Khác')], default='town_house', max_length=20, verbose_name='Loại BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(105.83549388560711, 20.976795401917798), help_text='Nhập toạ độ hoặc chọn vị trí trên bản đồ', null=True, srid=4326, verbose_name='Toạ độ vị trí BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Giá chào (tỷ)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor', verbose_name='Chuyên viên quản lý BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='receive_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Giá thu về (tỷ)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='registration_type',
            field=models.CharField(choices=[('red_pink_book', 'Sổ Đỏ/ Sổ hồng'), ('valid_documents', 'Giấy tờ hợp lệ'), ('construction_license', 'Giấy phép xây dựng'), ('business_license', 'Giấy phép kinh doanh'), ('prepare_book', 'Chuẩn bị làm sổ'), ('dont_book', 'Chưa có sổ'), ('other', 'Khác')], default='red_pink_book', max_length=20, verbose_name='Loại chứng nhận'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='reward_person',
            field=models.CharField(blank=True, help_text='Tên người chủ sở hữu BĐS. Ví dụ Nguyễn Văn A. Nếu BĐS của ĐC thì ghi tên của Chuyên viên ĐC và tên Cty', max_length=100, verbose_name='Tên chủ sở hữu BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='road_type',
            field=models.CharField(choices=[('alley_car_2', 'Ô tô tránh'), ('alley_car_tribike', 'Ô tô tránh Ba gác'), ('alley_car', 'Chỉ 1 Ô tô'), ('alley_tribike', 'Chỉ 1 Ba gác'), ('alley_tribike_bike', 'Ba gác tránh Xe máy'), ('alley_bike', 'Xe máy tránh nhau')], default='alley_car_tribike', max_length=20, verbose_name='Đường/Ngõ trước nhà'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Giá Hạ chào (tỷ)'),
        ),
    ]
