# Generated by Django 3.1.7 on 2021-11-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210815_1839'),
        ('listings', '0015_auto_20211119_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Giá TB/m2 (triệu)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='extra_data',
            field=models.TextField(blank=True, default='Chủ nhà hiểu chuyện, tôn trọng môi giới, thiện chí hợp tác,..', help_text='Ghi các thông tin khác quan trọng về chủ nhà hoặc các yếu tố khác liên quan đến tương tác với Chuyên viên...', max_length=500, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor', verbose_name='Chuyên viên quản lý BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='reward_person',
            field=models.CharField(blank=True, help_text='Tên người chủ sở hữu BĐS. Ví dụ Nguyễn Văn A. Nếu BĐS của ĐC thì ghi tên của Chuyên viên ĐC và tên Cty', max_length=100, verbose_name='Tên chủ sở hữu BĐS'),
        ),
    ]
