# Generated by Django 3.1.7 on 2022-05-01 08:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0015_auto_20220429_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Giá TB/m2 (triệu)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Thứ tự ưu tiên đăng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Người thêm BĐS'),
        ),
    ]
