# Generated by Django 3.1.7 on 2022-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20220501_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.CharField(default='NP2204HVH001', help_text='Chữ cái đầu Loại BĐS + 2 số cuối Năm Tháng + tên viết tắt Chuyên viên + Số BĐS của ĐC', max_length=80, unique=True, verbose_name='Mã BĐS (VIẾT HOA)'),
        ),
    ]
