# Generated by Django 3.1.7 on 2021-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20211127_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Giá TB/m2 (triệu)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='receive_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Giá thu về (tỷ)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Giá Hạ chào (tỷ)'),
        ),
    ]
