# Generated by Django 3.1.7 on 2022-05-13 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210815_1839'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0018_auto_20220505_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='realtors.realtor', verbose_name='Chuyên viên quản lý BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người thêm BĐS'),
        ),
        migrations.AlterField(
            model_name='listinghistory',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='realtors.realtor', verbose_name='Chuyên viên quản lý BĐS'),
        ),
        migrations.AlterField(
            model_name='listinghistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người thêm BĐS'),
        ),
    ]
