# Generated by Django 3.1.7 on 2021-12-14 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20211127_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Thứ tự ưu tiên đăng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Xây mới'), ('old', 'Nhà cũ'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Tình trạng BĐS'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='construction',
            field=models.CharField(blank=True, choices=[('release', 'Đã hoàn thiện'), ('under_construction', 'Đang thi công'), ('pre_release', 'Sắp thi công'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Tình trạng xây dựng'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='road_type',
            field=models.CharField(choices=[('alley_car_2', 'Ô tô tránh'), ('alley_car_tribike', 'Ô tô tránh Ba gác'), ('alley_car', 'Chỉ 1 Ô tô'), ('alley_tribike', 'Chỉ 1 Ba gác'), ('alley_tribike_bike', 'Ba gác tránh Xe máy'), ('alley_bike', 'Xe máy tránh nhau')], default='alley_car_tribike', max_length=20, verbose_name='Đường/Ngõ trước nhà'),
        ),
    ]
