# Generated by Django 3.1.7 on 2022-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20220513_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_advertising',
            field=models.BooleanField(default=False, verbose_name='LÀ TIN RAO VẶT'),
        ),
    ]
