# Generated by Django 3.1.7 on 2022-01-03 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20211214_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Thứ tự ưu tiên đăng'),
        ),
    ]
