# Generated by Django 3.1.7 on 2022-05-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_auto_20220527_1740'),
        ('listings', '0020_listing_is_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_advertising',
            field=models.BooleanField(default=False, verbose_name='LÀ TIN RAO VẶT'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='realtors.realtor', verbose_name='Chuyên viên quản lý BĐS'),
        ),
    ]
