# Generated by Django 3.1.7 on 2022-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20220427_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default=' Chú ý: Tất cả thông tin được đăng bởi TGNP đều là thông tin thật, xác thực chính xác.', help_text='Mô tả giới thiệu về BĐS ', verbose_name='Mô tả cho khách về bất động sản'),
        ),
    ]
