# Generated by Django 3.1.7 on 2022-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20220609_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default=' - Liên hệ: 0916286256 - 0964399436; 0971841941. <br> Chú ý: Tất cả thông tin được đăng bởi TGNP đều là thông tin thật, xác thực chính xác.', help_text='Mô tả giới thiệu về BĐS ', verbose_name='Mô tả cho khách về bất động sản'),
        ),
    ]
