# Generated by Django 3.1.14 on 2022-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20220716_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='exhaustive',
            field=models.CharField(choices=[('not', 'Chưa khảo sát'), ('prepare', 'Lên lịch chuẩn bị khảo sát'), ('investigated', 'Đã khảo sát')], default='not', max_length=20, verbose_name='Trạng thái khảo sát'),
        ),
        migrations.AddField(
            model_name='listing',
            name='expert_comments',
            field=models.TextField(blank=True, help_text='Chuyên gia đi khảo sát viết nhận xét nối tiếp ở đây', null=True, verbose_name='Nhận xét khảo sát'),
        ),
        migrations.AddField(
            model_name='listing',
            name='liquidity_classification',
            field=models.CharField(choices=[('super', 'A+_Cực dễ bán'), ('easy', 'A_Dễ bán'), ('normal', 'B_Bình thường'), ('hard', 'C_Khó bán'), ('very_hard', 'C_Rất khó bán'), ('not_rate', 'Chưa đánh giá')], default='not_rate', max_length=20, verbose_name='Phân loại thanh khoản'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Diện tích'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='area_real',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Diện tích thực tế'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Giá/m2 (triệu)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='ĐÃ KHẢO SÁT/ XÁC MINH TT CHUẨN'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Chiều dài'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Mặt tiền'),
        ),
    ]
