# Generated by Django 3.1.14 on 2022-08-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20220804_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.CharField(default='NP2206HH001', help_text='Chữ cái đầu Loại BĐS + 2 số cuối Năm Tháng + tên viết tắt Chuyên viên + Số BĐS của ĐC', max_length=80, unique=True, verbose_name='Mã BĐS (VIẾT HOA)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='ĐÃ XÁC THỰC'),
        ),
    ]
