# Generated by Django 3.1.14 on 2022-08-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20220804_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractimage',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.CharField(default='NPHH22083030', help_text='Chữ cái đầu Loại BĐS + tên viết tắt Chuyên viên + 2 số cuối Năm Tháng + Diện tích + Giá', max_length=80, unique=True, verbose_name='Mã BĐS (VIẾT HOA)'),
        ),
    ]
