# Generated by Django 3.1.14 on 2022-08-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20220812_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractimage',
            options={'verbose_name': 'Ảnh chụp hợp đồng, sổ đỏ, mặt tiền', 'verbose_name_plural': 'Ảnh hợp đồng, sổ đỏ'},
        ),
    ]
