# Generated by Django 3.1.14 on 2022-09-03 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20220816_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Bất động sản', 'verbose_name_plural': 'Bất động sản'},
        ),
        migrations.AlterModelOptions(
            name='listinghistory',
            options={'verbose_name': 'Bất động sản--Biến động', 'verbose_name_plural': 'Bất động sản--Biến động'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Ngày đăng bán/cho thuê'),
        ),
    ]
