# Generated by Django 3.1.14 on 2022-09-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_listing_full_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='listinghistory',
            old_name='list_date',
            new_name='date_created',
        ),
    ]
