# Generated by Django 3.1.14 on 2022-09-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_auto_20220906_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='full_path',
        ),
    ]
