# Generated by Django 3.1.14 on 2022-09-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_remove_listing_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='full_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
