# Generated by Django 3.1.14 on 2022-11-06 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_listing_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_update',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Ngày cập nhật'),
        ),
    ]
