# Generated by Django 4.1.3 on 2022-12-07 10:21

import FunctionModule.realtors.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Họ và tên')),
                ('position', models.CharField(choices=[('chairperson', 'Chủ tịch'), ('general_manager', 'Tổng giám đốc'), ('manager_director', 'Phó TGĐ/Giám đốc KD/ GĐ khối'), ('regional_director', 'Giám đốc khu vực/Bá tước'), ('manager', 'Giám đốc chuyên môn/Trưởng phòng'), ('leader', 'Trưởng bộ phận/Trưởng nhóm'), ('assistant', 'Trợ lý'), ('secretary', 'Thư ký'), ('accountant', 'Kế toán'), ('coordinator', 'Điều phối viên'), ('expert_home', 'Chuyên viên Đầu chủ'), ('expert', 'Chuyên viên'), ('interns', 'Học viên')], default='expert', max_length=20, verbose_name='Chức danh')),
                ('birthyear', models.IntegerField(blank=True, choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006)], null=True, verbose_name='Năm sinh')),
                ('countryside', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quê quán')),
                ('phone1', models.CharField(db_index=True, error_messages={'unique': 'Số điện thoại chính này đã được sử dụng trên hệ thống.'}, max_length=40, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại 10 số với chỉ các đầu số 09|03|07|08|05', regex='^(09|03|07|08|05)+([0-9]{8})$')], verbose_name='Điện thoại chính')),
                ('phone2', models.CharField(blank=True, db_index=True, error_messages={'unique': 'Số điện thoại phụ này đã được sử dụng trên hệ thống.'}, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại 10 số với chỉ các đầu số 09|03|07|08|05', regex='^(09|03|07|08|05)+([0-9]{8})$')], verbose_name='Điện thoại phụ')),
                ('avatar', models.ImageField(blank=True, upload_to='photos/avatar/', verbose_name='Ảnh đại diện')),
                ('identifier', models.CharField(blank=True, max_length=25, null=True, verbose_name='Căn cước công dân')),
                ('workplace', models.CharField(choices=[('tgnp', 'Thế Giới Nhà Phố Việt Nam'), ('thienkhoi', 'Thiên Khôi'), ('nhapho', 'Nhà Phố Việt Nam'), ('kimland', 'Kim Land'), ('tuan123', 'Tuấn 123'), ('phoxanh', 'Phố Xanh'), ('sumo', 'Sumo'), ('vuda', 'Vuda Home'), ('other', 'Đơn vị khác')], default='tgnp', max_length=50, verbose_name='Đơn vị')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bộ phận/Phòng/Ban')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi ở hiện tại')),
                ('title', models.CharField(choices=[('superman', 'Siêu nhân'), ('professor', 'Giáo sư'), ('expert', 'Chuyên gia'), ('master', 'Cao thủ'), ('competently', 'Thạo nghề'), ('probationary', 'Tập sự'), ('rookie', 'Tân binh')], default='rookie', max_length=30, verbose_name='Danh hiệu')),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Đẳng cấp chuyên môn')),
                ('work_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa bàn khu vực Quận/Huyện hoạt động')),
                ('story', models.TextField(blank=True, null=True, verbose_name='Kinh nghiệm hoạt động')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube')),
                ('training', models.CharField(blank=True, max_length=50, null=True, verbose_name='Khóa đào tạo')),
                ('referral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nguồn tuyển')),
                ('date_join', models.DateField(blank=True, default=FunctionModule.realtors.models.default_hire_date, null=True, verbose_name='Ngày vào đơn vị')),
                ('hire_date', models.DateField(blank=True, default=FunctionModule.realtors.models.default_hire_date, verbose_name='Ngày thêm chuyên viên')),
                ('status', models.CharField(choices=[('cooperating', 'Đang hợp tác'), ('pause_cooperating', 'Tạm dừng'), ('stop_cooperating', 'Ngừng hợp tác')], default='cooperating', max_length=20, verbose_name='Hợp tác với đơn vị cũ')),
                ('is_cooperate', models.BooleanField(default=False, verbose_name='ĐANG HỢP TÁC VỚI TGNP')),
                ('is_published', models.BooleanField(default=False, verbose_name='CÔNG KHAI DANH TÍNH')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đăng nhập của chuyên viên')),
            ],
            options={
                'verbose_name': 'Chuyên viên',
                'verbose_name_plural': 'Chuyên viên',
            },
        ),
    ]
