# Generated by Django 3.1.7 on 2021-05-05 17:16

import FunctionModule.realtors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=FunctionModule.realtors.models.default_hire_date),
        ),
    ]
