# Generated by Django 3.1.7 on 2021-08-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20210803_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Chuyên viên', 'verbose_name_plural': 'DS Chuyên viên'},
        ),
    ]
