# Generated by Django 3.1.7 on 2022-05-22 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210815_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Đẳng cấp chuyên môn'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='position',
            field=models.CharField(choices=[('chairperson', 'Chủ tịch'), ('general_manager', 'Tổng giám đốc'), ('manager_director', 'Giám đốc điều hành'), ('business_manager', 'Giám đốc kinh doanh'), ('regional_director', 'Giám đốc khu vực'), ('technical_director', 'Giám đốc kỹ thuật'), ('manager', 'Quản lý/Trưởng phòng'), ('assistant', 'Trợ lý'), ('accountant', 'Kế toán'), ('coordinator', 'Điều phối viên'), ('expert', 'Chuyên viên'), ('interns', 'Học viên'), ('user', 'Người dùng thông thường')], default='user', max_length=20, verbose_name='Chức danh'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='title',
            field=models.CharField(choices=[('professor', 'Giáo sư'), ('expert', 'Chuyên gia'), ('master', 'Cao thủ'), ('probationary', 'Tập sự'), ('rookie', 'Tân binh')], default='rookie', max_length=20, verbose_name='Danh hiệu'),
        ),
    ]
