# Generated by Django 3.1.7 on 2022-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_realtor_work_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='work_area',
            field=models.CharField(blank=True, default='Hoàng Mai', max_length=100, null=True, verbose_name='Địa bàn khu vực Quận/Huyện hoạt động'),
        ),
    ]
