# Generated by Django 3.1.7 on 2022-05-27 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_auto_20220527_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone2',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'Số điện thoại phụ này đã được sử dụng trên hệ thống.'}, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại 10 số với chỉ các đầu số 09|03|07|08|05', regex='^(09|03|07|08|05)+([0-9]{8})$')], verbose_name='Điện thoại phụ'),
        ),
    ]
