# Generated by Django 3.1.7 on 2022-06-09 14:01

import FunctionModule.realtors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0008_auto_20220527_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='date_join',
            field=models.DateTimeField(blank=True, default=FunctionModule.realtors.models.default_hire_date, verbose_name='Ngày vào đơn vị'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='identification',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Căn cước công dân'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='referral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nguồn tuyển'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='training',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Khóa đào tạo'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=FunctionModule.realtors.models.default_hire_date, verbose_name='Ngày thêm chuyên viên'),
        ),
    ]
