# Generated by Django 3.1.7 on 2022-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0010_auto_20220609_2118'),
    ]

    operations = [

    ]
