# Generated by Django 3.1.7 on 2022-06-09 14:34

import FunctionModule.realtors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0011_auto_20220609_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='countryside',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Quê quán'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='date_join',
            field=models.DateTimeField(blank=True, default=FunctionModule.realtors.models.default_hire_date, null=True, verbose_name='Ngày vào đơn vị'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='Kinh nghiệm hoạt động'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube'),
        ),
    ]
