# Generated by Django 3.1.7 on 2022-06-14 02:54

import FunctionModule.realtors.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0013_auto_20220609_2237'),
    ]

    operations = [

        migrations.AlterField(
            model_name='realtor',
            name='date_join',
            field=models.DateField(blank=True, default=FunctionModule.realtors.models.default_hire_date, null=True, verbose_name='Ngày vào đơn vị'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=FunctionModule.realtors.models.default_hire_date, verbose_name='Ngày thêm chuyên viên'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone2',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'Số điện thoại phụ này đã được sử dụng trên hệ thống.'}, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại 10 số với chỉ các đầu số 09|03|07|08|05', regex='^(09|03|07|08|05)+([0-9]{8})$')], verbose_name='Điện thoại phụ'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='status',
            field=models.CharField(choices=[('cooperating', 'Đang hợp tác'), ('pause_cooperating', 'Tạm dừng'), ('stop_cooperating', 'Ngừng hợp tác')], default='cooperating', max_length=20, verbose_name='Hợp tác với đơn vị cũ'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đăng nhập của chuyên viên'),
        ),
    ]
