# Generated by Django 3.1.14 on 2022-09-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0016_auto_20220804_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Chuyên viên', 'verbose_name_plural': 'Chuyên viên'},
        ),
    ]
