# Generated by Django 3.1.14 on 2022-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0017_auto_20220904_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='workplace',
            field=models.CharField(choices=[('tgnp', 'Thế Giới Nhà Phố Việt Nam'), ('thienkhoi', 'Thiên Khôi'), ('nhapho', 'Nhà Phố Việt Nam'), ('kimland', 'Kim Land'), ('tuan123', 'Tuấn 123'), ('phoxanh', 'Phố Xanh'), ('sumo', 'Sumo'), ('vuda', 'Vuda Home'), ('other', 'Đơn vị khác')], default='tgnp', max_length=50, verbose_name='Đơn vị'),
        ),
    ]
