# Generated by Django 3.1.14 on 2022-11-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0018_auto_20220909_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/%Y%m%d/', verbose_name='Ảnh đại diện'),
        ),
    ]
