# Generated by Django 3.1.14 on 2022-11-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0019_realtor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/avatar/', verbose_name='Ảnh đại diện'),
        ),
    ]
