# Generated by Django 3.1.7 on 2022-04-29 15:09

import FunctionModule.social_account.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[], max_length=30, verbose_name='Nhà cung cấp dịch vụ')),
                ('uid', models.CharField(max_length=191, verbose_name='uid')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Đăng nhập lần cuối')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tham gia')),
                ('extra_data', FunctionModule.social_account.fields.JSONField(default=dict, verbose_name='Ghi chú thêm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_user', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đăng nhập')),
            ],
            options={
                'verbose_name': 'Tài khoản mạng xã hội',
                'verbose_name_plural': 'Tài khoản mạng xã hội',
                'unique_together': {('provider', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='SocialApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[], max_length=30, verbose_name='Nhà cung cấp dịch vụ')),
                ('name', models.CharField(max_length=40, verbose_name='Tên ứng dụng')),
                ('client_id', models.CharField(help_text='ID ứng dụng hoặc khóa khách hàng', max_length=191, verbose_name='ID ứng dụng dùng đăng nhập')),
                ('secret', models.CharField(blank=True, help_text='API secret, client secret, or consumer secret', max_length=191, verbose_name='Khóa bí mật của ứng dụng')),
                ('key', models.CharField(blank=True, help_text='Khóa', max_length=191, verbose_name='Khóa')),
                ('sites', models.ManyToManyField(blank=True, related_name='django_site', to='sites.Site', verbose_name='Website dùng đăng nhập')),
            ],
            options={
                'verbose_name': 'Ứng dụng mạng xã hội',
                'verbose_name_plural': 'Ứng dụng mạng xã hội',
            },
        ),
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='"oauth_token" (OAuth1) hoặc token truy cập (OAuth2)', verbose_name='token')),
                ('token_secret', models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) hoặc token mới (OAuth2)', verbose_name='token secret')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_account.socialaccount')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_account.socialapp')),
            ],
            options={
                'verbose_name': 'Mã token ứng dụng xã hội',
                'verbose_name_plural': 'Mã token ứng dụng xã hội',
                'unique_together': {('app', 'account')},
            },
        ),
    ]
