# Generated by Django 4.1.3 on 2022-12-07 10:21

import FunctionModule.customers.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custormer_type', models.CharField(choices=[('buy_to_live', 'Mua ở'), ('keep_money', 'Đầu tư Giữ dòng tiền'), ('repair_construction', 'Đầu tư sửa bán'), ('invest_construction', 'Đầu tư xây bán'), ('surf_investment', 'Đầu tư lướt sóng'), ('rent_to_live', 'Thuê ở'), ('rent_to_office', 'Thuê làm văn phòng'), ('rent_to_restaurant', 'Thuê làm nhà hàng'), ('rent_to_shop', 'Thuê làm cửa hàng')], default='buy_to_live', max_length=20, verbose_name='Loại khách')),
                ('house_type', models.CharField(choices=[('street_house', 'Nhà mặt phố'), ('town_house', 'Nhà phố'), ('loft_house', 'Nhà 1 tầng/Cấp 4'), ('shop_house', 'Cửa hàng/ShopHouse'), ('apartment', 'Căn hộ/Chung cư MN/Nhà tập thể'), ('villa', 'Biệt thự'), ('plot', 'Liền kề/Phân lô/Dịch vụ'), ('land', 'Đất nền'), ('building', 'Toà nhà'), ('building_business', 'Toà nhà kinh doanh'), ('office', 'Văn phòng'), ('office_tel', 'Văn phòng khách sạn'), ('condo_tel', 'Căn hộ khách sạn'), ('service_apartment', 'Căn hộ dịch vụ'), ('pent_house', 'Căn hộ áp mái'), ('villa_rest', 'Biệt thự nghỉ dưỡng'), ('land_business', 'Mặt bằng kinh doanh'), ('industrial_land', 'Đất công nghiệp'), ('warehouse_workshop', 'Kho xưởng'), ('other', 'Khác')], default='town_house', max_length=20, verbose_name='Loại BĐS')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(db_index=True, error_messages={'unique': 'Số điện thoại này đã được người khác sử dụng trên hệ thống.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại 10 số với chỉ các đầu số 09|03|07|08|05', regex='^(09|03|07|08|05)+([0-9]{8})$')], verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'Email này đã được sử dụng trên hệ thống.'}, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ thường trú')),
                ('financial_range', models.DecimalField(decimal_places=2, help_text='Tài chính khách thu xếp được', max_digits=5, null=True, verbose_name='Tầm tài chính (tỷ)')),
                ('district', models.CharField(blank=True, help_text='Khu vực khách quan tâm. Dùng dấu phảy (,) để ngăn cách', max_length=500, null=True, verbose_name='Quận/Huyện quan tâm')),
                ('descriptions', models.TextField(blank=True, help_text='Nơi ở, nơi làm việc, nghề nghiệp, tình trạng hôn nhân,...Mục đích mua nhà (Để ở, đầu tư, để kinh doanh, vừa ở vừa kinh doanh). Khu vực nào? Vị trí mong muốn (gần đường, ngõ rộng,...)?. Có nhu cầu về ô tô hay không?,Khách có yêu cầu đi xem luôn hay không?,...', null=True, verbose_name='Thông tin, Nhu cầu cơ bản')),
                ('contact_from', models.CharField(blank=True, help_text='Khách tìm từ nguồn nào (Face, website, ai giới thiệu)? Liên hệ từ căn nào? BĐS thật hay chim mồi?...', max_length=500, null=True, verbose_name='Liên hệ từ đâu')),
                ('listing_watched', models.TextField(blank=True, help_text='Địa chỉ nhà đã xem? Ai dẫn xem? Thời gian xem? Ý kiến về BĐS này?,...', null=True, verbose_name='BĐS đã xem và phản hồi của khách')),
                ('status', models.CharField(choices=[('new', 'Mới đi xem nhà'), ('see_more', 'Xem nhiều nhưng chưa ưng BĐS nào'), ('have_buying', 'Đã từng mua/bán bđs'), ('missed_purchase', 'Đã từng chốt hụt')], default='see_more', help_text='Mới đi xem nhà. Cần mua gấp. Xem đã nhiều nhưng chưa ưng BĐS nào? Chốt hụt căn nào không?', max_length=50, verbose_name='Tình trạng chốt')),
                ('transactionStatus', models.CharField(choices=[('need', 'Cần mua/thuê gấp'), ('not_yet', 'Chưa mua/thuê'), ('pause_buying', 'Tạm dừng mua/thuê'), ('bought', 'Đã mua/thuê'), ('stop_buying', 'Dừng quan tâm')], default='not_yet', max_length=50, verbose_name='Trạng thái giao dịch')),
                ('classify', models.CharField(choices=[('focused_care', 'Khách nét. Cần chăm tập trung'), ('normal_care', 'Chăm bình thường'), ('slowly_care', 'Chăm từ từ'), ('stop_care', 'Dừng chăm sóc'), ('again_care', 'Chăm sóc lại')], default='normal_care', help_text='Cần chăm tập trung? Chăm bình thường? Chăm từ từ?', max_length=50, verbose_name='Kết luận chăm khách')),
                ('hire_date', models.DateField(blank=True, default=FunctionModule.customers.models.default_hire_date, verbose_name='Thời điểm thêm')),
                ('last_interaction', models.DateField(blank=True, default=FunctionModule.customers.models.default_hire_date, verbose_name='Thời điểm tương tác gần nhất')),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='realtors.realtor', verbose_name='Giao Chuyên viên chăm sóc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người thêm KH')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
            },
        ),
    ]
