# Generated by Django 3.1.7 on 2021-09-04 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210904_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='potential_points',
            field=models.IntegerField(blank=True, default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm tiềm năng'),
        ),
    ]
