# Generated by Django 3.1.7 on 2022-05-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210904_1714'),
        ('customers', '0002_auto_20220429_2209'),
    ]

    operations = [
    ]
