# Generated by Django 3.1.7 on 2021-09-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210904_1934'),
        ('customers', '0004_auto_20210904_1936'),
    ]

    operations = [
    ]
