# Generated by Django 3.1.14 on 2022-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20220804_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='request',
        ),
        migrations.AlterField(
            model_name='customer',
            name='descriptions',
            field=models.TextField(blank=True, help_text='Nơi ở, nơi làm việc, nghề nghiệp, tình trạng hôn nhân,...Mục đích mua nhà (Để ở, đầu tư, để kinh doanh, vừa ở vừa kinh doanh). Khu vực nào? Vị trí mong muốn (gần đường, ngõ rộng,...)?. Có nhu cầu về ô tô hay không?,Khách có yêu cầu đi xem luôn hay không?,...', null=True, verbose_name='Thông tin, Nhu cầu cơ bản'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, help_text='Khu vực khách quan tâm. Dùng dấu phảy (,) để ngăn cách', max_length=500, null=True, verbose_name='Quận/Huyện quan tâm'),
        ),
    ]
