# Generated by Django 3.1.7 on 2021-11-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20211119_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Tên khách hàng'),
        ),
    ]
