# Generated by Django 3.1.14 on 2022-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20220816_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house_type',
            field=models.CharField(choices=[('street_house', 'Nhà mặt phố'), ('town_house', 'Nhà phố'), ('loft_house', 'Nhà 1 tầng/Cấp 4'), ('shop_house', 'Cửa hàng/ShopHouse'), ('apartment', 'Căn hộ/Chung cư MN/Nhà tập thể'), ('villa', 'Biệt thự'), ('plot', 'Liền kề/Phân lô/Dịch vụ'), ('land', 'Đất nền'), ('building', 'Toà nhà'), ('building_business', 'Toà nhà kinh doanh'), ('office', 'Văn phòng'), ('office_tel', 'Văn phòng khách sạn'), ('condo_tel', 'Căn hộ khách sạn'), ('service_apartment', 'Căn hộ dịch vụ'), ('pent_house', 'Căn hộ áp mái'), ('villa_rest', 'Biệt thự nghỉ dưỡng'), ('land_business', 'Mặt bằng kinh doanh'), ('industrial_land', 'Đất công nghiệp'), ('warehouse_workshop', 'Kho xưởng'), ('other', 'Khác')], default='town_house', max_length=20, verbose_name='Loại BĐS'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='classify',
            field=models.CharField(choices=[('focused_care', 'Khách nét. Cần chăm tập trung'), ('normal_care', 'Chăm bình thường'), ('slowly_care', 'Chăm từ từ'), ('stop_care', 'Dừng chăm sóc'), ('again_care', 'Chăm sóc lại')], default='normal_care', help_text='Cần chăm tập trung? Chăm bình thường? Chăm từ từ?', max_length=50, verbose_name='Kết luận chăm khách'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custormer_type',
            field=models.CharField(choices=[('buy_to_live', 'Mua ở'), ('keep_money', 'Đầu tư Giữ dòng tiền'), ('repair_construction', 'Đầu tư sửa bán'), ('invest_construction', 'Đầu tư xây bán'), ('surf_investment', 'Đầu tư lướt sóng'), ('rent_to_live', 'Thuê ở'), ('rent_to_office', 'Thuê làm văn phòng'), ('rent_to_restaurant', 'Thuê làm nhà hàng'), ('rent_to_shop', 'Thuê làm cửa hàng')], default='buy_to_live', max_length=20, verbose_name='Loại khách'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'Mới đi xem nhà'), ('see_more', 'Xem nhiều nhưng chưa ưng BĐS nào'), ('have_buying', 'Đã từng mua/bán bđs'), ('missed_purchase', 'Đã từng chốt hụt')], default='see_more', help_text='Mới đi xem nhà. Cần mua gấp. Xem đã nhiều nhưng chưa ưng BĐS nào? Chốt hụt căn nào không?', max_length=50, verbose_name='Tình trạng chốt'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='transactionStatus',
            field=models.CharField(choices=[('need', 'Cần mua/thuê gấp'), ('not_yet', 'Chưa mua/thuê'), ('pause_buying', 'Tạm dừng mua/thuê'), ('bought', 'Đã mua/thuê'), ('stop_buying', 'Dừng quan tâm')], default='not_yet', max_length=50, verbose_name='Trạng thái giao dịch'),
        ),
    ]
