# Generated by Django 3.1.14 on 2022-09-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20220901_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
    ]
