# Generated by Django 3.1.7 on 2021-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, help_text='Khu vực Quận/Huyện khách quan tâm BĐS', max_length=255, null=True, verbose_name='Quận/Huyện'),
        ),
    ]
