# Generated by Django 3.1.7 on 2021-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20211119_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(help_text='Khu vực Quận/Huyện khách quan tâm BĐS. Dùng dấu phảy (,) để ngăn cách quận huyện', max_length=255, verbose_name='Quận/Huyện'),
        ),
    ]
