# Generated by Django 3.1.7 on 2021-11-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20211119_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='potential_points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='realtor',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
