# Generated by Django 3.1.7 on 2021-11-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210815_1839'),
        ('customers', '0013_auto_20211119_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor', verbose_name='Chuyên viên phụ trách'),
        ),
    ]
