# Generated by Django 3.1.7 on 2021-11-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0016_auto_20211119_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, help_text='Khu vực Quận/Huyện khách quan tâm BĐS. Dùng dấu phảy (,) để ngăn cách quận huyện', max_length=255, null=True, verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Người thêm KH'),
        ),
    ]
