# Generated by Django 3.1.7 on 2021-12-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_auto_20211122_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='classify',
            field=models.CharField(choices=[('focused_care', 'Cần chăm tập trung'), ('normal_care', 'Chăm bình thường'), ('slowly_care', 'Chăm từ từ'), ('stop_care', 'Dừng chăm sóc'), ('again_care', 'Chăm sóc lại'), ('bought', 'Đã mua nhà rồi')], default='focused_care', help_text='Cần chăm tập trung? Chăm bình thường? Chăm từ từ?', max_length=50, verbose_name='Phân loại khách'),
        ),
    ]
