# Generated by Django 3.1.7 on 2022-04-27 08:19

import FunctionModule.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20220104_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='classify',
            field=models.CharField(choices=[('focused_care', 'Cần chăm tập trung'), ('normal_care', 'Chăm bình thường'), ('slowly_care', 'Chăm từ từ'), ('stop_care', 'Dừng chăm sóc'), ('again_care', 'Chăm sóc lại')], default='focused_care', help_text='Cần chăm tập trung? Chăm bình thường? Chăm từ từ?', max_length=50, verbose_name='Kết luận chăm khách'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_from',
            field=models.CharField(blank=True, help_text='Khách tìm từ nguồn nào (Face, website, giới thiệu)? Liên hệ từ căn nào? BĐS thật hay chim mồi?...', max_length=500, null=True, verbose_name='Liên hệ từ đâu'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='descriptions',
            field=models.TextField(blank=True, help_text='Nơi ở, nơi làm việc, nghề nghiệp, tình trạng hôn nhân,...Mục đích mua nhà (Để ở, đầu tư, để kinh doanh, vừa ở vừa kinh doanh). Khu vực nào? Vị trí mong muốn (gần đường, ngõ rộng,...)?. Có nhu cầu về ô tô hay không?,Khách có yêu cầu đi xem luôn hay không?,...', null=True, verbose_name='Thông tin nhu cầu cơ bản'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, help_text='Khu vực khách quan tâm. Dùng dấu phảy (,) để ngăn cách', max_length=500, null=True, verbose_name='Khu vực quan tâm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hire_date',
            field=models.DateField(blank=True, default=FunctionModule.customers.models.default_hire_date, verbose_name='Thời điểm thêm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_interaction',
            field=models.DateField(blank=True, default=FunctionModule.customers.models.default_hire_date, verbose_name='Thời điểm tương tác gần nhất'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='listing_watched',
            field=models.TextField(blank=True, help_text='Địa chỉ nhà đã xem? Ai dẫn xem? Thời gian xem? Ý kiến về BĐS này?,...', null=True, verbose_name='BĐS đã xem và phản hồi của khách'),
        ),
    ]
