# Generated by Django 3.1.7 on 2021-06-06 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('house_type', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('request_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=256)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='session_key',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
