# Generated by Django 4.1.3 on 2022-12-07 10:21

import FunctionModule.hitcount.models
import datetime
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.TextField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('market', 'Thị trường'), ('invest', 'Đầu tư'), ('enterprise', 'Doanh nghiệp'), ('identify', 'Chuyên gia trao đổi'), ('zoning', 'Quy hoạch'), ('project', 'Dự án'), ('utility', 'Dịch vụ & Tiện ích '), ('policy', 'Chính sách & Pháp luật')], default='market', max_length=20, verbose_name='Loại tin tức')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề tin')),
                ('content', models.TextField(verbose_name='Nội dung tin')),
                ('is_published', models.BooleanField(default=True, verbose_name='CHO PHÉP ĐĂNG')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Thời gian đăng')),
                ('date_update', models.DateField(default=datetime.datetime.now, verbose_name='Cập nhật')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng tin')),
            ],
            options={
                'verbose_name': 'Tin bài',
                'verbose_name_plural': 'Tin bài',
            },
            bases=(models.Model, FunctionModule.hitcount.models.HitCountMixin),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'content'], name='blog_post_title_657ad7_gin'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['title'], name='blog_post_title_7c2d8e_btree'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['title', 'content'], name='blog_post_title_74ba3d_btree'),
        ),
    ]
