# Generated by Django 3.1.7 on 2022-06-22 16:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20150512_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Tin bài', 'verbose_name_plural': 'DS Bài viết'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'content'], name='blog_post_title_657ad7_gin'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['title'], name='blog_post_title_7c2d8e_btree'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['title', 'content'], name='blog_post_title_74ba3d_btree'),
        ),
    ]
