# Generated by Django 3.1.14 on 2022-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220904_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='CHO PHÉP ĐĂNG'),
        ),
    ]
