# Generated by Django 3.1.14 on 2022-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220906_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='full_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
