# Generated by Django 3.1.14 on 2022-09-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220906_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='full_path',
        ),
    ]
