# Generated by Django 3.1.14 on 2022-09-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('market', 'Thị trường'), ('invest', 'Đầu tư'), ('enterprise', 'Doanh nghiệp'), ('identify', 'Chuyên gia trao đổi'), ('zoning', 'Quy hoạch'), ('project', 'Dự án'), ('utility', 'Dịch vụ & Tiện ích '), ('policy', 'Chính sách & Pháp luật')], default='market', max_length=20, verbose_name='Loại tin tức'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Nội dung tin'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề tin'),
        ),
    ]
