# Generated by Django 3.1.14 on 2022-11-08 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220911_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_update',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Cập nhật'),
        ),
    ]
