INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (13, 'Can add content type', 4, 'add_contenttype');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (14, 'Can change content type', 4, 'change_contenttype');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (15, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (16, 'Can view content type', 4, 'view_contenttype');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (17, 'Can add session', 5, 'add_session');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (18, 'Can change session', 5, 'change_session');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (19, 'Can delete session', 5, 'delete_session');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (20, 'Can view session', 5, 'view_session');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (21, 'Can add user', 6, 'add_user');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (22, 'Can change user', 6, 'change_user');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (23, 'Can delete user', 6, 'delete_user');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (24, 'Can view user', 6, 'view_user');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (25, 'Can add listing', 7, 'add_listing');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (26, 'Can change listing', 7, 'change_listing');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (27, 'Can delete listing', 7, 'delete_listing');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (28, 'Can view listing', 7, 'view_listing');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (29, 'Can add listing video', 8, 'add_listingvideo');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (30, 'Can change listing video', 8, 'change_listingvideo');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (31, 'Can delete listing video', 8, 'delete_listingvideo');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (32, 'Can view listing video', 8, 'view_listingvideo');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (33, 'Can add listing image', 9, 'add_listingimage');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (34, 'Can change listing image', 9, 'change_listingimage');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (35, 'Can delete listing image', 9, 'delete_listingimage');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (36, 'Can view listing image', 9, 'view_listingimage');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (37, 'Can add realtor', 10, 'add_realtor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (38, 'Can change realtor', 10, 'change_realtor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (39, 'Can delete realtor', 10, 'delete_realtor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (40, 'Can view realtor', 10, 'view_realtor');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (41, 'Can add contact', 11, 'add_contact');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (42, 'Can change contact', 11, 'change_contact');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (43, 'Can delete contact', 11, 'delete_contact');
INSERT INTO "auth_permission"("id", "name", "content_type_id", "codename") VALUES (44, 'Can view contact', 11, 'view_contact');
